# Generated by Django 4.0.5 on 2022-06-26 20:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=130, verbose_name='Subtítulo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('image', models.ImageField(upload_to='photos')),
                ('content_post', ckeditor.fields.RichTextField(verbose_name='Contenido del post')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
