# Generated by Django 4.0.5 on 2022-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, height_field='1080', null=True, upload_to='images/', width_field='1080'),
        ),
    ]
